### ISSUE TITLE
文件无法下载

### ISSUE THREAD

**Issue by 114514-1919810-bit** [fR0Z863xF/fudisk#1]
感谢大佬分享的工具，但使用下来发现两个问题。
1.文件上传成功后不会直接提示，要切到其他页面后再切回来才能刷新
2.文件无法下载，例如这个链接https://s.100tifen.com/media/tk/exercise/2024/08-18/t8559481/2ordblde4r.pdf
最后问下，辅利码课的工作人员能不能监测到我们哪些账号一直上传文件？

**Comment by fR0Z863xF** [comment]
ui没写好，小bug等功能做全了再修。 

你的账号配置可能有问题，~~我检查逻辑没写好~~具体bug还不清楚，换别人账号试一下。保存完记得切主页看一下，这时候会有提示。

这个bug我明天试一下，现在没测试环境

**Comment by fR0Z863xF** [comment]
> 辅利码课的工作人员能不能监测到我们哪些账号一直上传文件？  

不清楚，如果那边有api统计的话可以；如果没有的话，通过分析日志也可以找到。不过后者需要人工查，约等于没有监测

**Comment by 114514-1919810-bit** [comment]
好的，谢谢

**Comment by fR0Z863xF** [comment]
别急，过几分钟发新版，刚刚编译完

**Comment by fR0Z863xF** [comment]
0.2 release已发，请更新
